name: Greet on Push

on: 
  push:
    branches:
      - '**'  # This matches all branches

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "👋 Hello, thank you for your push!"
          echo "Pushed by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"

